#!/bin/bash

clear

# Change directory to the directory of the script
export DOTFILES_FOLDER=`pwd`

# Abort on error
set -e

function usage(){
  printf "\nHow to use :\n"
  printf "  -c : Only create symlink for config files and configure macos\n"
  printf "  -s : Only install softwares\n"
  printf "  -h : Show this help\n"
}

export USE_APPS=1
export USE_CONFIG=1

while getopts "hcs" option
do
  case $option in
    h)
      usage;
      exit 0;;
    c)
      echo "Skipping software installation step";
      unset USE_APPS
      shift;;
    s)
      echo "Skipping system config step";
      unset USE_CONFIG
      shift;;
    \?)
      usage
      exit 1
      ;;
  esac
done;

# ## Install macos specific apps and config
sh $DOTFILES_FOLDER/macos/setup.sh

unset USE_APPS
unset USE_CONFIG
unset DOTFILES_FOLDER
