runtime! config/**/*.vim

set number
set encoding=UTF-8
set relativenumber
set clipboard=unnamed
set clipboard=unnamedplus

let mapleader = ","

filetype plugin indent on
syntax on

nnoremap <C-p> :Files<CR>
nnoremap <C-f> :Rg<CR>
inoremap kj <C-C>
inoremap jk <C-C>

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'mattn/emmet-vim'

Plug 'dense-analysis/ale'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'vim-airline/vim-airline'
Plug 'editorconfig/editorconfig-vim'

call plug#end()

" NERDTree config
autocmd VimEnter * NERDTree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

" ALE config
let g:ale_fix_on_save = 1
let g:ale_completion_autoimport = 1
let g:ale_fixers = {
\   'javascript': ['prettier', 'eslint'], 
\   'typescript': ['eslint'],
\   'vue': ['eslint'],
\}
